//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTEWeb_DailyJob.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=bk_ate_server;Initial Catalog=ate_result;Persist Security Info=True;U" +
            "ser ID=ate_oper;Password=ate.oper")]
        public string ate_resultConnectionString {
            get {
                return ((string)(this["ate_resultConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=shiwpd-atesqlR;Initial Catalog=ate_db_tblfinal_new;User ID=ate_oper;P" +
            "assword=ate.oper")]
        public string ate_db_tblfinal_newConnectionString {
            get {
                return ((string)(this["ate_db_tblfinal_newConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=shiwpd-atesqlR;Initial Catalog=ate_result_h;User ID=ate_oper;Password" +
            "=ate.oper")]
        public string ate_result_hConnectionString {
            get {
                return ((string)(this["ate_result_hConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=shiwpd-atesqlR;Initial Catalog=ate_db_tblfinal_new;Persist Security I" +
            "nfo=True;User ID=ate_oper;Password=ate.oper")]
        public string ate_db_tblfinal_newConnectionString1 {
            get {
                return ((string)(this["ate_db_tblfinal_newConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=shiwpd-atesqlR;Initial Catalog=ate_result_h;Persist Security Info=Tru" +
            "e;User ID=ate_oper;Password=ate.oper")]
        public string ate_result_hConnectionString1 {
            get {
                return ((string)(this["ate_result_hConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHIWPD-ATESQLR;Initial Catalog=ate_db_tblfinal_new;User ID=ate_oper")]
        public string ate_db_tblfinal_newConnectionString2 {
            get {
                return ((string)(this["ate_db_tblfinal_newConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHIWPD-ATESQLR;Initial Catalog=ate_db_tblfinal_new;User ID=ate_oper;P" +
            "assword=ate.oper")]
        public string ate_db_tblfinal_newConnectionString3 {
            get {
                return ((string)(this["ate_db_tblfinal_newConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SHIWPD-ATESQLR;Initial Catalog=ate_db_tblfinal_new;Persist Security I" +
            "nfo=True;User ID=ate_oper")]
        public string ate_db_tblfinal_newConnectionString4 {
            get {
                return ((string)(this["ate_db_tblfinal_newConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=shiwpd-atesqlR;Initial Catalog=ate_result_h;Persist Security Info=Tru" +
            "e;User ID=ate_oper")]
        public string ate_result_hConnectionString2 {
            get {
                return ((string)(this["ate_result_hConnectionString2"]));
            }
        }
    }
}
