//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTEWeb_DailyJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemName
    {
        public short ItemNameType { get; set; }
        public string Name1 { get; set; }
        public string Name2 { get; set; }
        public string Name3 { get; set; }
        public string Name4 { get; set; }
        public string Name5 { get; set; }
        public string Name6 { get; set; }
        public string Name7 { get; set; }
        public string Name8 { get; set; }
        public string Name9 { get; set; }
        public string Name10 { get; set; }
        public string Name11 { get; set; }
        public string Name12 { get; set; }
        public string Name13 { get; set; }
        public string Name14 { get; set; }
        public string Name15 { get; set; }
        public string Name16 { get; set; }
        public string Name17 { get; set; }
        public string Name18 { get; set; }
        public string Name19 { get; set; }
        public string Name20 { get; set; }
        public string Name21 { get; set; }
        public string Name22 { get; set; }
        public string Name23 { get; set; }
        public string Name24 { get; set; }
        public string Name25 { get; set; }
        public string Name26 { get; set; }
        public string Name27 { get; set; }
        public string Name28 { get; set; }
        public string Name29 { get; set; }
        public string Name30 { get; set; }
        public string Name31 { get; set; }
        public string Name32 { get; set; }
        public string Name33 { get; set; }
        public string Name34 { get; set; }
        public string Name35 { get; set; }
        public string Name36 { get; set; }
        public string Name37 { get; set; }
        public string Name38 { get; set; }
        public string Name39 { get; set; }
        public string Name40 { get; set; }
        public string Name41 { get; set; }
        public string Name42 { get; set; }
        public string Name43 { get; set; }
        public string Name44 { get; set; }
        public string Name45 { get; set; }
        public string Name46 { get; set; }
        public string Name47 { get; set; }
        public string Name48 { get; set; }
        public string Name49 { get; set; }
        public string Name50 { get; set; }
        public string Name51 { get; set; }
        public string Name52 { get; set; }
        public string Name53 { get; set; }
        public string Name54 { get; set; }
        public string Name55 { get; set; }
        public string Name56 { get; set; }
        public string Name57 { get; set; }
        public string Name58 { get; set; }
        public string Name59 { get; set; }
        public string Name60 { get; set; }
        public string Name61 { get; set; }
        public string Name62 { get; set; }
        public string Name63 { get; set; }
        public string Name64 { get; set; }
        public string Name65 { get; set; }
        public string Name66 { get; set; }
        public string Name67 { get; set; }
        public string Name68 { get; set; }
        public string Name69 { get; set; }
        public string Name70 { get; set; }
        public string Name71 { get; set; }
        public string Name72 { get; set; }
        public string Name73 { get; set; }
        public string Name74 { get; set; }
        public string Name75 { get; set; }
        public string Name76 { get; set; }
        public string Name77 { get; set; }
        public string Name78 { get; set; }
        public string Name79 { get; set; }
        public string Name80 { get; set; }
        public string Name81 { get; set; }
        public string Name82 { get; set; }
        public string Name83 { get; set; }
        public string Name84 { get; set; }
        public string Name85 { get; set; }
        public string Name86 { get; set; }
        public string Name87 { get; set; }
        public string Name88 { get; set; }
        public string Name89 { get; set; }
        public string Name90 { get; set; }
        public string Name91 { get; set; }
        public string Name92 { get; set; }
        public string Name93 { get; set; }
        public string Name94 { get; set; }
        public string Name95 { get; set; }
        public string Name96 { get; set; }
        public string Name97 { get; set; }
        public string Name98 { get; set; }
        public string Name99 { get; set; }
        public string Name100 { get; set; }
        public string Name101 { get; set; }
        public string Name102 { get; set; }
        public string Name103 { get; set; }
        public string Name104 { get; set; }
        public string Name105 { get; set; }
        public string Name106 { get; set; }
        public string Name107 { get; set; }
        public string Name108 { get; set; }
        public string Name109 { get; set; }
        public string Name110 { get; set; }
        public string Name111 { get; set; }
        public string Name112 { get; set; }
        public string Name113 { get; set; }
        public string Name114 { get; set; }
        public string Name115 { get; set; }
        public string Name116 { get; set; }
        public string Name117 { get; set; }
        public string Name118 { get; set; }
        public string Name119 { get; set; }
        public string Name120 { get; set; }
        public string Name121 { get; set; }
        public string Name122 { get; set; }
        public string Name123 { get; set; }
        public string Name124 { get; set; }
        public string Name125 { get; set; }
        public string Name126 { get; set; }
        public string Name127 { get; set; }
        public string Name128 { get; set; }
        public string Name129 { get; set; }
        public string Name130 { get; set; }
        public string Name131 { get; set; }
        public string Name132 { get; set; }
        public string Name133 { get; set; }
        public string Name134 { get; set; }
        public string Name135 { get; set; }
        public string Name136 { get; set; }
        public string Name137 { get; set; }
        public string Name138 { get; set; }
        public string Name139 { get; set; }
        public string Name140 { get; set; }
        public string Name141 { get; set; }
        public string Name142 { get; set; }
        public string Name143 { get; set; }
        public string Name144 { get; set; }
        public string Name145 { get; set; }
        public string Name146 { get; set; }
        public string Name147 { get; set; }
        public string Name148 { get; set; }
        public string Name149 { get; set; }
        public string Name150 { get; set; }
        public Nullable<int> ORG_ID { get; set; }
        public string Station { get; set; }
        public string ItemDescription { get; set; }
    }
}
