//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTEWeb_DailyJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTEWEB_ItemNameType_ByDaily_TOP10_FailItem
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public int ItemNameType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Total_Fail_Count { get; set; }
        public string No1_Fail_Item { get; set; }
        public Nullable<int> No1_Fail_Count { get; set; }
        public Nullable<double> No1_Fail_Rate { get; set; }
        public string No2_Fail_Item { get; set; }
        public Nullable<int> No2_Fail_Count { get; set; }
        public Nullable<double> No2_Fail_Rate { get; set; }
        public string No3_Fail_Item { get; set; }
        public Nullable<int> No3_Fail_Count { get; set; }
        public Nullable<double> No3_Fail_Rate { get; set; }
        public string No4_Fail_Item { get; set; }
        public Nullable<int> No4_Fail_Count { get; set; }
        public Nullable<double> No4_Fail_Rate { get; set; }
        public string No5_Fail_Item { get; set; }
        public Nullable<int> No5_Fail_Count { get; set; }
        public Nullable<double> No5_Fail_Rate { get; set; }
        public string No6_Fail_Item { get; set; }
        public Nullable<int> No6_Fail_Count { get; set; }
        public Nullable<double> No6_Fail_Rate { get; set; }
        public string No7_Fail_Item { get; set; }
        public Nullable<int> No7_Fail_Count { get; set; }
        public Nullable<double> No7_Fail_Rate { get; set; }
        public string No8_Fail_Item { get; set; }
        public Nullable<int> No8_Fail_Count { get; set; }
        public Nullable<double> No8_Fail_Rate { get; set; }
        public string No9_Fail_Item { get; set; }
        public Nullable<int> No9_Fail_Count { get; set; }
        public Nullable<double> No9_Fail_Rate { get; set; }
        public string No10_Fail_Item { get; set; }
        public Nullable<int> No10_Fail_Count { get; set; }
        public Nullable<double> No10_Fail_Rate { get; set; }
        public string Org { get; set; }
    }
}
