//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTEWeb_DailyJob.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PTEWEB_ItemNameType_ByDaily_TOP10_LongCycleTime
    {
        public int id { get; set; }
        public System.DateTime Date { get; set; }
        public string Org { get; set; }
        public int ItemNameType { get; set; }
        public string Discription { get; set; }
        public Nullable<double> Avg_Pass_Time { get; set; }
        public Nullable<double> Avg_Total_Time { get; set; }
        public string NO1_Item { get; set; }
        public Nullable<double> NO1_CycleTime { get; set; }
        public Nullable<double> NO1_Percent { get; set; }
        public string NO2_Item { get; set; }
        public Nullable<double> NO2_CycleTime { get; set; }
        public Nullable<double> NO2_Percent { get; set; }
        public string NO3_Item { get; set; }
        public Nullable<double> NO3_CycleTime { get; set; }
        public Nullable<double> NO3_Percent { get; set; }
        public string NO4_Item { get; set; }
        public Nullable<double> NO4_CycleTime { get; set; }
        public Nullable<double> NO4_Percent { get; set; }
        public string NO5_Item { get; set; }
        public Nullable<double> NO5_CycleTime { get; set; }
        public Nullable<double> NO5_Percent { get; set; }
        public string NO6_Item { get; set; }
        public Nullable<double> NO6_CycleTime { get; set; }
        public Nullable<double> NO6_Percent { get; set; }
        public string NO7_Item { get; set; }
        public Nullable<double> NO7_CycleTime { get; set; }
        public Nullable<double> NO7_Percent { get; set; }
        public string NO8_Item { get; set; }
        public Nullable<double> NO8_CycleTime { get; set; }
        public Nullable<double> NO8_Percent { get; set; }
        public string NO9_Item { get; set; }
        public Nullable<double> NO9_CycleTime { get; set; }
        public Nullable<double> NO9_Percent { get; set; }
        public string NO10_Item { get; set; }
        public Nullable<double> NO10_CycleTime { get; set; }
        public Nullable<double> NO10_Percent { get; set; }
    }
}
